// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block/block.proto

/*
Package block is a generated protocol buffer package.

It is generated from these files:
	block/block.proto

It has these top-level messages:
	Signature
	Transaction
	Petition
	Block
	PublicKey
	PrivateKey
*/
package block

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction_Type int32

const (
	Transaction_Raw       Transaction_Type = 0
	Transaction_PublicKey Transaction_Type = 1
)

var Transaction_Type_name = map[int32]string{
	0: "Raw",
	1: "PublicKey",
}
var Transaction_Type_value = map[string]int32{
	"Raw":       0,
	"PublicKey": 1,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// metadat about a block signature
type Signature struct {
	Timestamp  int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Hash       []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	SignatureA []byte `protobuf:"bytes,3,opt,name=signatureA,proto3" json:"signatureA,omitempty"`
	SignatureB []byte `protobuf:"bytes,4,opt,name=signatureB,proto3" json:"signatureB,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signature) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Signature) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Signature) GetSignatureA() []byte {
	if m != nil {
		return m.SignatureA
	}
	return nil
}

func (m *Signature) GetSignatureB() []byte {
	if m != nil {
		return m.SignatureB
	}
	return nil
}

type Transaction struct {
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	Payload   []byte     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transaction) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Petition struct {
	Hash       []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Signatures []*Signature `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *Petition) Reset()                    { *m = Petition{} }
func (m *Petition) String() string            { return proto.CompactTextString(m) }
func (*Petition) ProtoMessage()               {}
func (*Petition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Petition) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Petition) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// Metadata about a block
type Block struct {
	Timestamp    int64          `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Parent       []byte         `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Petition     *Petition      `protobuf:"bytes,3,opt,name=petition" json:"petition,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,4,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Block) GetPetition() *Petition {
	if m != nil {
		return m.Petition
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type PublicKey struct {
	X    []byte `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    []byte `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Hint string `protobuf:"bytes,3,opt,name=hint" json:"hint,omitempty"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PublicKey) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *PublicKey) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

func (m *PublicKey) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

type PrivateKey struct {
	Public *PublicKey `protobuf:"bytes,1,opt,name=public" json:"public,omitempty"`
	D      []byte     `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`
}

func (m *PrivateKey) Reset()                    { *m = PrivateKey{} }
func (m *PrivateKey) String() string            { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()               {}
func (*PrivateKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PrivateKey) GetPublic() *PublicKey {
	if m != nil {
		return m.Public
	}
	return nil
}

func (m *PrivateKey) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func init() {
	proto.RegisterType((*Signature)(nil), "block.Signature")
	proto.RegisterType((*Transaction)(nil), "block.Transaction")
	proto.RegisterType((*Petition)(nil), "block.Petition")
	proto.RegisterType((*Block)(nil), "block.Block")
	proto.RegisterType((*PublicKey)(nil), "block.PublicKey")
	proto.RegisterType((*PrivateKey)(nil), "block.PrivateKey")
	proto.RegisterEnum("block.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
}

func init() { proto.RegisterFile("block/block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0x57, 0xb1, 0xf3, 0xc7, 0x93, 0x2c, 0x9b, 0xd5, 0x61, 0xf1, 0x61, 0x09, 0xc1, 0xa5,
	0x10, 0x28, 0x38, 0x25, 0x85, 0x5e, 0x7a, 0xaa, 0xe9, 0xad, 0x17, 0xa3, 0xe6, 0xd4, 0x9b, 0xec,
	0x88, 0x58, 0xd4, 0xb6, 0x84, 0xad, 0x34, 0xf1, 0xa1, 0x2f, 0xd3, 0x27, 0x2d, 0x56, 0x64, 0xc7,
	0x09, 0x85, 0x5e, 0x84, 0x46, 0xdf, 0xcc, 0xe8, 0x37, 0x9f, 0x04, 0x7f, 0xa3, 0x54, 0xc4, 0x6f,
	0x4b, 0xbd, 0xfa, 0xb2, 0x10, 0x4a, 0xe0, 0xbe, 0x0e, 0xbc, 0x0f, 0x70, 0x5e, 0xf8, 0x36, 0xa7,
	0x6a, 0x57, 0x30, 0xfc, 0x1f, 0x1c, 0xc5, 0x33, 0x56, 0x2a, 0x9a, 0x49, 0x17, 0xcd, 0xd1, 0xc2,
	0x22, 0xa7, 0x03, 0x8c, 0xc1, 0x4e, 0x68, 0x99, 0xb8, 0xbd, 0x39, 0x5a, 0x4c, 0x88, 0xde, 0xe3,
	0x19, 0x40, 0xd9, 0x94, 0x3f, 0xba, 0x96, 0x56, 0x3a, 0x27, 0x67, 0x7a, 0xe0, 0xda, 0x17, 0x7a,
	0xe0, 0xed, 0x61, 0xbc, 0x2e, 0x68, 0x5e, 0xd2, 0x58, 0x71, 0x91, 0x63, 0x1f, 0x9c, 0x56, 0xd4,
	0x00, 0xe3, 0xd5, 0xd4, 0x3f, 0x52, 0xb7, 0x94, 0xe4, 0x94, 0x82, 0x5d, 0x18, 0x4a, 0x5a, 0xa5,
	0x82, 0x6e, 0x0c, 0x55, 0x13, 0x7a, 0x33, 0xb0, 0xd7, 0x95, 0x64, 0x78, 0x08, 0x16, 0xa1, 0xfb,
	0xe9, 0x2f, 0xfc, 0x1b, 0x9c, 0x70, 0x17, 0xa5, 0x3c, 0x7e, 0x66, 0xd5, 0x14, 0x79, 0x21, 0x8c,
	0x42, 0xa6, 0xb8, 0xbe, 0xb5, 0x19, 0x0c, 0x75, 0x06, 0xbb, 0xed, 0x80, 0x97, 0x6e, 0x6f, 0x6e,
	0x7d, 0x8b, 0xd2, 0xc9, 0xf1, 0x3e, 0x11, 0xf4, 0x83, 0x5a, 0xff, 0xc1, 0xc6, 0x7f, 0x30, 0x90,
	0xb4, 0x60, 0xb9, 0x32, 0xc8, 0x26, 0xc2, 0x37, 0x30, 0x92, 0x86, 0x48, 0x1b, 0x39, 0x5e, 0xfd,
	0x31, 0xf7, 0x35, 0xa0, 0xa4, 0x4d, 0xc0, 0xf7, 0x30, 0x51, 0x27, 0xdf, 0x4a, 0xd7, 0xd6, 0x80,
	0xd8, 0x14, 0x74, 0x2c, 0x25, 0x67, 0x79, 0xde, 0x43, 0xc7, 0x05, 0x3c, 0x01, 0x74, 0x30, 0x43,
	0xa3, 0x43, 0x1d, 0x55, 0x06, 0x09, 0x55, 0xda, 0x13, 0x9e, 0x2b, 0x4d, 0xe2, 0x10, 0xbd, 0xf7,
	0x9e, 0x00, 0xc2, 0x82, 0xbf, 0x53, 0xc5, 0xea, 0xea, 0x05, 0x0c, 0xa4, 0x6e, 0x75, 0xf1, 0x50,
	0x6d, 0x7f, 0x62, 0xf4, 0xba, 0x73, 0xf3, 0x3e, 0x68, 0x13, 0x5c, 0xbf, 0x5e, 0x6d, 0xb9, 0x4a,
	0x76, 0x91, 0x1f, 0x8b, 0x6c, 0xc9, 0x52, 0x2e, 0x54, 0xc2, 0x36, 0x2c, 0xa3, 0xf9, 0x32, 0x61,
	0x54, 0x25, 0xc7, 0x5f, 0x1a, 0x0d, 0xf4, 0x37, 0xbd, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0x8a, 0x26, 0x3f, 0xbb, 0x02, 0x00, 0x00,
}
