// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block/block.proto

/*
Package block is a generated protocol buffer package.

It is generated from these files:
	block/block.proto

It has these top-level messages:
	Signature
	Transaction
	Petition
	Block
	PublicKey
	PrivateKey
*/
package block

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// metadat about a block signature
type Signature struct {
	Timestamp  *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Hash       []byte                     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	SignatureA []byte                     `protobuf:"bytes,3,opt,name=signatureA,proto3" json:"signatureA,omitempty"`
	SignatureB []byte                     `protobuf:"bytes,4,opt,name=signatureB,proto3" json:"signatureB,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signature) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Signature) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Signature) GetSignatureA() []byte {
	if m != nil {
		return m.SignatureA
	}
	return nil
}

func (m *Signature) GetSignatureB() []byte {
	if m != nil {
		return m.SignatureB
	}
	return nil
}

type Transaction struct {
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	Payload   []byte     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transaction) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Petition struct {
	Hash       []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Signatures []*Signature `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *Petition) Reset()                    { *m = Petition{} }
func (m *Petition) String() string            { return proto.CompactTextString(m) }
func (*Petition) ProtoMessage()               {}
func (*Petition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Petition) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Petition) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// Metadata about a block
type Block struct {
	Timestamp    *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Parent       []byte                     `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Petition     *Petition                  `protobuf:"bytes,3,opt,name=petition" json:"petition,omitempty"`
	Transactions []*Transaction             `protobuf:"bytes,4,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Block) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Block) GetPetition() *Petition {
	if m != nil {
		return m.Petition
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type PublicKey struct {
	X []byte `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y []byte `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PublicKey) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *PublicKey) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type PrivateKey struct {
	Public *PublicKey `protobuf:"bytes,1,opt,name=public" json:"public,omitempty"`
	D      []byte     `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`
}

func (m *PrivateKey) Reset()                    { *m = PrivateKey{} }
func (m *PrivateKey) String() string            { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()               {}
func (*PrivateKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PrivateKey) GetPublic() *PublicKey {
	if m != nil {
		return m.Public
	}
	return nil
}

func (m *PrivateKey) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func init() {
	proto.RegisterType((*Signature)(nil), "block.Signature")
	proto.RegisterType((*Transaction)(nil), "block.Transaction")
	proto.RegisterType((*Petition)(nil), "block.Petition")
	proto.RegisterType((*Block)(nil), "block.Block")
	proto.RegisterType((*PublicKey)(nil), "block.PublicKey")
	proto.RegisterType((*PrivateKey)(nil), "block.PrivateKey")
}

func init() { proto.RegisterFile("block/block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x6b, 0xbb, 0x30,
	0x1c, 0xc6, 0x49, 0xff, 0xfd, 0xea, 0xb7, 0x85, 0xdf, 0x96, 0xc3, 0x90, 0x1e, 0xb6, 0xe2, 0x18,
	0x2b, 0x0c, 0x74, 0x74, 0x30, 0x76, 0x9d, 0xec, 0xb6, 0x8b, 0xb8, 0xc2, 0x60, 0xb7, 0x68, 0x33,
	0x0d, 0x53, 0x23, 0x1a, 0x47, 0x7d, 0x29, 0x7b, 0x33, 0x7b, 0x6d, 0xc3, 0x98, 0x58, 0x5b, 0x76,
	0xdb, 0x45, 0xfc, 0xe6, 0x79, 0xf2, 0xf8, 0xc9, 0x13, 0xe1, 0x34, 0x48, 0x78, 0xf8, 0xe1, 0xc8,
	0xa7, 0x9d, 0x17, 0x5c, 0x70, 0x3c, 0x96, 0xc3, 0xe2, 0x22, 0xe2, 0x3c, 0x4a, 0xa8, 0x23, 0x17,
	0x83, 0xea, 0xdd, 0x11, 0x2c, 0xa5, 0xa5, 0x20, 0x69, 0xde, 0xfa, 0xac, 0x2f, 0x04, 0xc6, 0x0b,
	0x8b, 0x32, 0x22, 0xaa, 0x82, 0xe2, 0x07, 0x30, 0x3a, 0x83, 0x89, 0x96, 0x68, 0x35, 0x5b, 0x2f,
	0xec, 0x36, 0xc2, 0xd6, 0x11, 0xf6, 0x46, 0x3b, 0xfc, 0xbd, 0x19, 0x63, 0x18, 0xc5, 0xa4, 0x8c,
	0xcd, 0xc1, 0x12, 0xad, 0xe6, 0xbe, 0x7c, 0xc7, 0xe7, 0x00, 0xa5, 0x8e, 0x7e, 0x34, 0x87, 0x52,
	0xe9, 0xad, 0x1c, 0xe8, 0xae, 0x39, 0x3a, 0xd2, 0x5d, 0xeb, 0x15, 0x66, 0x9b, 0x82, 0x64, 0x25,
	0x09, 0x05, 0xe3, 0x19, 0xb6, 0xc1, 0xe8, 0x44, 0x05, 0x77, 0x62, 0xb7, 0x67, 0xee, 0x4e, 0xe0,
	0xef, 0x2d, 0xd8, 0x84, 0x7f, 0x39, 0xa9, 0x13, 0x4e, 0xb6, 0x8a, 0x4a, 0x8f, 0x96, 0x07, 0x53,
	0x8f, 0x0a, 0x26, 0x53, 0x35, 0x38, 0xea, 0x81, 0xdf, 0xf6, 0xc0, 0x4a, 0x73, 0xb0, 0x1c, 0xfe,
	0xfa, 0xa9, 0x9e, 0xc7, 0xfa, 0x46, 0x30, 0x76, 0x1b, 0xfd, 0x0f, 0x15, 0x9e, 0xc1, 0x24, 0x27,
	0x05, 0xcd, 0x84, 0xc2, 0x55, 0x13, 0xbe, 0x81, 0x69, 0xae, 0x68, 0x65, 0x89, 0xb3, 0xf5, 0x7f,
	0xc5, 0xa2, 0x0f, 0xe1, 0x77, 0x06, 0x7c, 0x0f, 0x73, 0xb1, 0xef, 0xac, 0x34, 0x47, 0x12, 0x1e,
	0xab, 0x0d, 0xbd, 0x3a, 0xfd, 0x03, 0x9f, 0x75, 0x0d, 0x86, 0x57, 0x05, 0x09, 0x0b, 0x9f, 0x69,
	0x8d, 0xe7, 0x80, 0x76, 0xaa, 0x10, 0xb4, 0x6b, 0xa6, 0x5a, 0x21, 0xa1, 0xda, 0x7a, 0x02, 0xf0,
	0x0a, 0xf6, 0x49, 0x04, 0x6d, 0x9c, 0x2b, 0x98, 0xe4, 0x72, 0xdb, 0xd1, 0x85, 0x74, 0x59, 0xbe,
	0xd2, 0x9b, 0x14, 0x7d, 0x0f, 0x68, 0xeb, 0x5e, 0xbd, 0x5d, 0x46, 0x4c, 0xc4, 0x55, 0x60, 0x87,
	0x3c, 0x75, 0x68, 0xc2, 0xb8, 0x88, 0xe9, 0x96, 0xa6, 0x24, 0x73, 0x62, 0x4a, 0x44, 0xdc, 0xfe,
	0xcb, 0xc1, 0x44, 0x36, 0x76, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x08, 0x1b, 0xe5, 0xa2, 0xe1,
	0x02, 0x00, 0x00,
}
